### PR TITLE
AIM support

### PR DESCRIPTION
**Pull request by Glorfindel83**
Rudimentary support for AIM in the chat screen. TODO:
- fix scrolling
- load AIM only for Charcoal HQ, not for other webpages
- debugging
- ...

### CODE REVIEW

**Comment by NobodyNada** [comment]
Thanks!  I'm a leader at my church's middle school camp right now, so I won't be able to review this for a little bit.

**Comment by Glorfindel83** [comment]
No problem, I'll probably add a few commits in the meantime as well. Have a blessed time!

**Comment by NobodyNada** [comment]
Thank you, I had an awesome time! This looks great; thanks!

**Comment by Glorfindel83** [comment]
Thanks. You might want to implement the fix described here:
https://chat.stackexchange.com/transcript/message/39278822#39278822
(too lazy to create a PR right now)

**Comment by NobodyNada** [comment]
Thanks!  I'll try to get to that this afternoon.

**Pull request merged**
